### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Kankkune** [Raision-seudun-koulutuskuntayhtyma/VSCode-Python#3]
ettet vahihingossa ylikirjoita
https://github.com/Raision-seudun-koulutuskuntayhtyma/VSCode-Python/wiki/7.-Kirjastot-ja-modulit#modulien-lataaminen-p%C3%A4%C3%A4ohjelmaan

---------------

 josta python ohjelma on käynnstetty
https://github.com/Raision-seudun-koulutuskuntayhtyma/VSCode-Python/wiki/7.-Kirjastot-ja-modulit#modulin-luominen

**Comment by MikaVainio** [comment]
Korjattu
